---
- name: Install Docker
  hosts: all
  become: yes

  tasks:
    - name: Install Dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl 
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add ubuntu user to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    - name: check ubuntu user groups
      ansible.builtin.command: groups ubuntu
      register: ubuntu_groups

    - name: Show ubuntu user groups
      ansible.builtin.debug:
      msg: "Ubuntu user belogs to groups: {{ ubuntu_groups.stdout }}"

    - name: Reboot the server to apply group changes
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible after Docker Installation"
        connect_timeout: 5
        reboot_timeout: 300
