---
- name: Install Docker
  hosts: all
  become: yes

  tasks:
    - name: Install Dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl 
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add ubuntu user to docker group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: docker
        append: yes
      loop:
        - ubuntu
        - jenkins

    - name: check ubuntu user groups
      ansible.builtin.command: "groups {{ item }}"
      register: user_groups
      loop:
        - ubuntu
        - jenkins

    - name: Show User groups
      ansible.builtin.debug:
        msg: "{{ item.item }} belongs to groups: {{ item.stdout }}"
      loop: "{{ user_groups.results }}"

    - name: Reboot the server
      reboot:
        msg: "Rebooting after group change"
        connect_timeout: 5
        reboot_timeout: 120
        pre_reboot_delay: 5
        post_reboot_delay: 30      
